// SPDX-License-Identifier: MIT
pragma solidity 0.7.5;

import "../BaseTreasury.sol";

/**
 * @title TCAP Arbitrum Treasury
 * @author Cryptex.finance
 * @notice This contract will hold the assets generated by the arbitrum network.
 */
contract ArbitrumTreasury is BaseTreasury {
  /**
   * @notice Constructor
   * @param _owner the owner of the contract
   **/
  constructor(address _owner) BaseTreasury(_owner) {}

  /// @notice renounceOwnership has been disabled so that the contract is never left without a owner
  /// @inheritdoc Proprietor
  function renounceOwnership() public override onlyOwner {
    revert("ArbitrumTreasury::renounceOwnership: function disabled");
  }
}
