[profile.default]
optimizer = true
optimizer_runs = 20000
fuzz_runs = 100
verbosity= 2
gas_reports = ["*"]
no_match_contract = "Fork"

[profile.fork]
optimizer = true
optimizer_runs = 20000
fuzz_runs = 100
verbosity= 2
gas_reports = ["*"]
no_match_contract = "Bar"
match_contract = "Fork"

[profile.ci]
fuzz_runs = 10000
